# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "97944c95688f416e014a460b304a1f27"
application_url = "https://canvas-katie-exists-math.trycloudflare.com"
embedded = true
name = "sc-recom"
handle = "sc-recom"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://canvas-katie-exists-math.trycloudflare.com/auth/callback",
  "https://canvas-katie-exists-math.trycloudflare.com/auth/shopify/callback",
  "https://canvas-katie-exists-math.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
